<a href="https://colab.research.google.com/github/brianvansteen/linearAlgebra/blob/main/linearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
asList  = [1,2,3]
asArray = np.array([1,2,3]) # 1D array or vector
rowVec  = np.array([ [1,2,3] ]) # row
colVec  = np.array([ [1],[2],[3] ]) # column

In [4]:
print(f'asList:  {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec:  {rowVec.shape}')
print(f'colVec:  {colVec.shape}')

asList:  (3,)
asArray: (3,)
rowVec:  (1, 3)
colVec:  (3, 1)


## PyTorch

In [5]:
xPT = torch.tensor(25)
xPT

tensor(25)

In [6]:
xPT.shape

torch.Size([])

## TensorFlow

In [7]:
xTF = tf.Variable(30, dtype=tf.int32)
xTF

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=30>

In [8]:
xTF.shape

TensorShape([])

In [9]:
yTF = tf.Variable(22)
yTF

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=22>

In [10]:
tfSum = tf.add(xTF, yTF)
tfSum

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [11]:
sum = tfSum.numpy()
sum

52

In [12]:
type(tfSum)

tensorflow.python.framework.ops.EagerTensor

In [13]:
type(sum)

numpy.int32

# Vectors (Rank 1 Tensors) in NumPy

In [14]:
x = np.array([15, 83, 3, 18]) # 1D array, 1 dimension space
x

array([15, 83,  3, 18])

In [15]:
len(x)

4

In [16]:
x.shape

(4,)

In [17]:
type(x)

numpy.ndarray

In [18]:
type(x[1])

numpy.int64

In [19]:
xT = x.T
xT

array([15, 83,  3, 18])

In [20]:
xT.shape

(4,)

In [21]:
x2 = np.array([[38, 7, 82, 55]]) # matrix brackets, 2 dimension space
x2

array([[38,  7, 82, 55]])

In [22]:
x2.shape

(1, 4)

In [23]:
type(x2)

numpy.ndarray

In [24]:
x2T = x2.T
x2T

array([[38],
       [ 7],
       [82],
       [55]])

In [25]:
x2T.shape

(4, 1)

In [26]:
type(x2T)

numpy.ndarray

In [27]:
i = np.array([1, 0])
j = np.array([0, 1])
i, j

(array([1, 0]), array([0, 1]))

## Dot Product

[1, 0] dot [0, 1] = 1*0 + 0*1 = 0

In [45]:
np.dot(i, j)

0

# Norms

$L^2$

$L^1$

Represent magnitude and direction from origin.

I.e., Pythagoreum function.

In [28]:
# L2 norm, ||x||2 or ||x|| is assumped to be L2 norm
np.linalg.norm(xT)

86.29600222490032

In [29]:
(xT[0]**2 + xT[1]**2 + xT[2]**2 +xT[3]**2)**(1/2)

86.29600222490032

In [30]:
np.linalg.norm(x2T)

106.02829810951414

In [31]:
np.linalg.norm(x2)

106.02829810951414

## If ||x|| = 1, x is unit vector

In [32]:
# L1 norm, ||x||1
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2]) + np.abs(x[3])

119

In [33]:
# Squared L2 norm
(xT[0]**2 + xT[1]**2 + xT[2]**2 +xT[3]**2)

7447

In [34]:
xT

array([15, 83,  3, 18])

In [35]:
x

array([15, 83,  3, 18])

In [36]:
np.dot(x, x)

7447

In [37]:
np.dot(xT, xT)

7447

In [38]:
l2sq = x*xT
l2sq

array([ 225, 6889,    9,  324])

In [39]:
print(np.sum(l2sq))

7447


## 2 Dimension

In [40]:
x2

array([[38,  7, 82, 55]])

In [41]:
x2T

array([[38],
       [ 7],
       [82],
       [55]])

In [42]:
print(x2*x2T)

[[1444  266 3116 2090]
 [ 266   49  574  385]
 [3116  574 6724 4510]
 [2090  385 4510 3025]]


In [43]:
print(np.dot(x2, x2T))

[[11242]]


In [44]:
print(np.sum((x2*x2T)))

33124


# Matrix

In [46]:
X = np.array([[25, 2], [5, 26], [3, 7]])

In [47]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [48]:
X.shape

(3, 2)

In [49]:
X.size

6